# Generated by Django 5.0.2 on 2024-03-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('average_rating', models.FloatField()),
                ('image_url', models.URLField()),
            ],
        ),
    ]
