# Generated by Django 5.0.4 on 2024-05-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0004_book_y_pub_book_publisher_book_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Y_Pub',
            field=models.CharField(default='1950', max_length=255),
        ),
    ]
